// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IAirService is an autogenerated mock type for the IAirService type
type IAirService struct {
	mock.Mock
}

// GetAirActual provides a mock function with given fields:
func (_m *IAirService) GetAirActual() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIAirService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIAirService creates a new instance of IAirService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIAirService(t mockConstructorTestingTNewIAirService) *IAirService {
	mock := &IAirService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
