// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IBudgetHandler is an autogenerated mock type for the IBudgetHandler type
type IBudgetHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *IBudgetHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// Delete provides a mock function with given fields: c
func (_m *IBudgetHandler) Delete(c *gin.Context) {
	_m.Called(c)
}

// GetAll provides a mock function with given fields: c
func (_m *IBudgetHandler) GetAll(c *gin.Context) {
	_m.Called(c)
}

// GetByCode provides a mock function with given fields: c
func (_m *IBudgetHandler) GetByCode(c *gin.Context) {
	_m.Called(c)
}

// NewIBudgetHandler creates a new instance of IBudgetHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBudgetHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBudgetHandler {
	mock := &IBudgetHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
