// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "shared-wallet-service/infrastructure/cache/model"

	mock "github.com/stretchr/testify/mock"
)

// ICacheClient is an autogenerated mock type for the ICacheClient type
type ICacheClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *ICacheClient) Get(key string) (model.User, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.User
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (model.User, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) model.User); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetByNickName provides a mock function with given fields: nickName
func (_m *ICacheClient) GetByNickName(nickName string) (model.User, bool) {
	ret := _m.Called(nickName)

	if len(ret) == 0 {
		panic("no return value specified for GetByNickName")
	}

	var r0 model.User
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (model.User, bool)); ok {
		return rf(nickName)
	}
	if rf, ok := ret.Get(0).(func(string) model.User); ok {
		r0 = rf(nickName)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(nickName)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, user
func (_m *ICacheClient) Set(key string, user model.User) {
	_m.Called(key, user)
}

// NewICacheClient creates a new instance of ICacheClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICacheClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICacheClient {
	mock := &ICacheClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
