// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	request "docker-go-project/api/dto/request"

	mock "github.com/stretchr/testify/mock"

	response "docker-go-project/api/dto/response"
)

// IGroupService is an autogenerated mock type for the IGroupService type
type IGroupService struct {
	mock.Mock
}

// CreateGroup provides a mock function with given fields: ctx, groupDTO
func (_m *IGroupService) CreateGroup(ctx context.Context, groupDTO request.GroupDTO) error {
	ret := _m.Called(ctx, groupDTO)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.GroupDTO) error); ok {
		r0 = rf(ctx, groupDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetGroupByCode provides a mock function with given fields: ctx, code
func (_m *IGroupService) GetGroupByCode(ctx context.Context, code string) (response.GroupResponse, error) {
	ret := _m.Called(ctx, code)

	var r0 response.GroupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (response.GroupResponse, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) response.GroupResponse); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(response.GroupResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroups provides a mock function with given fields: ctx
func (_m *IGroupService) GetGroups(ctx context.Context) ([]response.GroupResponse, error) {
	ret := _m.Called(ctx)

	var r0 []response.GroupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]response.GroupResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []response.GroupResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.GroupResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDebtByCode provides a mock function with given fields: ctx, groupDTO
func (_m *IGroupService) UpdateDebtByCode(ctx context.Context, groupDTO request.GroupDTO) error {
	ret := _m.Called(ctx, groupDTO)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.GroupDTO) error); ok {
		r0 = rf(ctx, groupDTO)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIGroupService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIGroupService creates a new instance of IGroupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIGroupService(t mockConstructorTestingTNewIGroupService) *IGroupService {
	mock := &IGroupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
