// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IJob is an autogenerated mock type for the IJob type
type IJob struct {
	mock.Mock
}

// UserCache provides a mock function with no fields
func (_m *IJob) UserCache() {
	_m.Called()
}

// NewIJob creates a new instance of IJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *IJob {
	mock := &IJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
