// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "shared-wallet-service/domain/user/dto"

	mock "github.com/stretchr/testify/mock"
)

// IKeycloakRepository is an autogenerated mock type for the IKeycloakRepository type
type IKeycloakRepository struct {
	mock.Mock
}

// GetUsers provides a mock function with given fields: ctx
func (_m *IKeycloakRepository) GetUsers(ctx context.Context) ([]dto.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []dto.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIKeycloakRepository creates a new instance of IKeycloakRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIKeycloakRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IKeycloakRepository {
	mock := &IKeycloakRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
