// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// IPingHandler is an autogenerated mock type for the IPingHandler type
type IPingHandler struct {
	mock.Mock
}

// Ping provides a mock function with given fields: c
func (_m *IPingHandler) Ping(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewIPingHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewIPingHandler creates a new instance of IPingHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIPingHandler(t mockConstructorTestingTNewIPingHandler) *IPingHandler {
	mock := &IPingHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
