// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ITeamHandler is an autogenerated mock type for the ITeamHandler type
type ITeamHandler struct {
	mock.Mock
}

// ComposeTeam provides a mock function with given fields: c
func (_m *ITeamHandler) ComposeTeam(c *gin.Context) {
	_m.Called(c)
}

// DecomposeTeam provides a mock function with given fields: c
func (_m *ITeamHandler) DecomposeTeam(c *gin.Context) {
	_m.Called(c)
}

// GetTeamByGroup provides a mock function with given fields: c
func (_m *ITeamHandler) GetTeamByGroup(c *gin.Context) {
	_m.Called(c)
}

// GetTeamsByUser provides a mock function with given fields: c
func (_m *ITeamHandler) GetTeamsByUser(c *gin.Context) {
	_m.Called(c)
}

// NewITeamHandler creates a new instance of ITeamHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITeamHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITeamHandler {
	mock := &ITeamHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
