// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	team "docker-go-project/pkg/repository/team"

	mock "github.com/stretchr/testify/mock"
)

// ITeamRepository is an autogenerated mock type for the ITeamRepository type
type ITeamRepository struct {
	mock.Mock
}

// ComposeTeam provides a mock function with given fields: ctx, _a1
func (_m *ITeamRepository) ComposeTeam(ctx context.Context, _a1 team.Team) (int64, error) {
	ret := _m.Called(ctx, _a1)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, team.Team) (int64, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, team.Team) int64); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, team.Team) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DecomposeTeam provides a mock function with given fields: ctx, _a1
func (_m *ITeamRepository) DecomposeTeam(ctx context.Context, _a1 team.Team) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, team.Team) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExistUserInTeam provides a mock function with given fields: ctx, id
func (_m *ITeamRepository) ExistUserInTeam(ctx context.Context, id int64) (bool, error) {
	ret := _m.Called(ctx, id)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersByGroup provides a mock function with given fields: ctx, code
func (_m *ITeamRepository) GetUsersByGroup(ctx context.Context, code string) ([]string, error) {
	ret := _m.Called(ctx, code)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewITeamRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewITeamRepository creates a new instance of ITeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewITeamRepository(t mockConstructorTestingTNewITeamRepository) *ITeamRepository {
	mock := &ITeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
