// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	request "docker-go-project/api/dto/request"

	mock "github.com/stretchr/testify/mock"

	response "docker-go-project/api/dto/response"
)

// ITeamService is an autogenerated mock type for the ITeamService type
type ITeamService struct {
	mock.Mock
}

// ComposeTeam provides a mock function with given fields: ctx, code, teamRequest
func (_m *ITeamService) ComposeTeam(ctx context.Context, code string, teamRequest request.TeamRequest) error {
	ret := _m.Called(ctx, code, teamRequest)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.TeamRequest) error); ok {
		r0 = rf(ctx, code, teamRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecomposeTeam provides a mock function with given fields: ctx, code, teamRequest
func (_m *ITeamService) DecomposeTeam(ctx context.Context, code string, teamRequest request.TeamRequest) error {
	ret := _m.Called(ctx, code, teamRequest)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, request.TeamRequest) error); ok {
		r0 = rf(ctx, code, teamRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUsersByGroup provides a mock function with given fields: ctx, code
func (_m *ITeamService) GetUsersByGroup(ctx context.Context, code string) (response.TeamUsersResponse, error) {
	ret := _m.Called(ctx, code)

	var r0 response.TeamUsersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (response.TeamUsersResponse, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) response.TeamUsersResponse); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(response.TeamUsersResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewITeamService interface {
	mock.TestingT
	Cleanup(func())
}

// NewITeamService creates a new instance of ITeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewITeamService(t mockConstructorTestingTNewITeamService) *ITeamService {
	mock := &ITeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
