// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	iwrite "shared-wallet-service/infrastructure/database/interfaces/write"

	mock "github.com/stretchr/testify/mock"
)

// IWriteDataBase is an autogenerated mock type for the IWriteDataBase type
type IWriteDataBase struct {
	mock.Mock
}

// Write provides a mock function with no fields
func (_m *IWriteDataBase) Write() iwrite.IWrite {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 iwrite.IWrite
	if rf, ok := ret.Get(0).(func() iwrite.IWrite); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iwrite.IWrite)
		}
	}

	return r0
}

// NewIWriteDataBase creates a new instance of IWriteDataBase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIWriteDataBase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IWriteDataBase {
	mock := &IWriteDataBase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
