name: LOCAL
mysql:
  user: cow
  password: Admin123
  port: 3306
  host: shared-wallet-service-db
  schema: shared-wallet-service-db
keycloak:
  url: http://host.docker.internal:8080
  timeout: 5s
  client_id: cow
  realm: SSO
  client_secret: 7pljySAaUv7sgpJYpjJCwlIcMNxD2bBp
job:
  users:
    active: true
    expression: 0/1 * * * *